### PR TITLE
[FEATURE] Implemented Epitope per Index plots

### PR DESCRIPTION
**Pull request by Zethson**
Hey,

just for you to test it out I still left the data that you provided me in the python script.
You can and should delete it eventually.

Both plots are created simultaneously and can be viewed at the same time.

Before
image

After
image

### CODE REVIEW

**Comment by Zethson** [comment]
I just noticed that the "after" plot features a different looking x-axis. This is likely due to me creating two plots.

I don't think that it's an issue, or is it @steffenlem?

**Review by steffenlem — CHANGES_REQUESTED** [review]
The data is only plotted up to the position of the last epitope. If the last positions of the sequence do not contribute to a binding core, they are not included in the plot. This could cause a big difference in both plots, since we are of course removing epitopes.
Labled axis would also be nice. I would also suggest to use only a single color?

**Comment by Zethson** [comment]
Thanks for the feedback. I addressed all requested changes.
Not sure whether or not "all red" really looks better.

Note that you now have to pass the size of the protein in order to fill up missing values for the "before" state as well.

**Comment by Zethson** [comment]
Before:
image

After: 
image

Looks fine to me now.

**Pull request merged**
